### ISSUE TITLE
makebigwigfiles bedtools genomecov error

### ISSUE THREAD

**Issue by Enidanellani** [YeoLab/eclip#1]
Hello eclip team!

I'm trying to use your pipeline for single-end eclip analysis which I got from github.
However, when I try to run the small example you provide (cwl-runner ../cwl/wf_get_peaks_scatter_se.cwl single_end_clip_small.yaml), I obtain the following error when making bigwig files:
*****ERROR: Unrecognized parameter: -du *****
This error is related to the bedtools genomecov function called in one of the make_bigwig_files.py scripts. In one of these scripts, the "-du" flag is called, although bedtools genomecov does not have this option.
When I went through the make_bigwig_files.py scipts in my environment
(/envs/clip-seq/lib/python2.7/site-packages/gscripts-0.1.6-py2.7.egg/gscripts/general/make_bigwig_files.py
or
envs/clip-seq/lib/python2.7/site-packages/gscripts-0.1.6-py2.7.egg/EGG-INFO/scripts/make_bigwig_files.py)
I cannot find the "-du" flag.
However, the same script in your github repository (https://github.com/YeoLab/makebigwigfiles/blob/master/makebigwigfiles/make_bigwig_files.py) shows the "-du" option which needs to be removed.
Could you please indicate where I find the make_bigwig_files.py script is located that is called by the program, so I can manually remove the "-du" which will most probably solve my issue.
Thank you so much for your help!
All the best,
Nina

**Comment by byee4** [comment]
Which version of bedtools are you using? Bedtools 2.27.1 should have the -du flag available

**Comment by byee4** [comment]
bedtools genomecov:         
```
-du             Change strand af the mate read (so both reads from the same strand) useful for strand specific
                        Works for BAM files only
```

Thanks for letting us know about the version discrepancy, we'll update the documentation.
