### ISSUE TITLE
Could not lead extension Schema

### ISSUE THREAD

**Issue by peaceben** [YeoLab/eclip#11]
Hi,

i run into an early error using docker and cwl, when running ./pairend_end.yaml. Do you have any advice how to resolve the error?

Best regards,
Ben

The log file beginns with this error:

/usr/bin/cwltool 1.0.20180302231433
Resolved '/home/linux/Desktop/eclip/cwl/wf_get_peaks_scatter_pe.cwl' to 'file:///home/linux/Desktop/eclip/cwl/wf_get_peaks_scatter_pe.cwl'
No handlers could be found for logger "rdflib.term"
Could not load extension schema http://schema.org/docs/schema_org_rdfa.html: RDFa parsing Error! mismatched tag: line 21, column 2
../eclip/cwl/samtools-index.cwl:7:1: unrecognized extension field `http://schema.org/mainEntity`.  Did you include a $schemas section?
../eclip/cwl/samtools-index.cwl:7:1: unrecognized extension field `http://schema.org/downloadUrl`.  Did you include a $schemas section?
../eclip/cwl/samtools-index.cwl:7:1: unrecognized extension field `http://schema.org/codeRepository`.  Did you include a $schemas section?
../eclip/cwl/samtools-index.cwl:7:1: unrecognized extension field `http://schema.org/license`.  Did you include a $schemas section?
../eclip/cwl/samtools-index.cwl:7:1: unrecognized extension field `http://schema.org/isPartOf`.  Did you include a $schemas section?
../eclip/cwl/samtools-index.cwl:7:1: unrecognized extension field `http://schema.org/author`.  Did you include a $schemas section?
../eclip/cwl/samtools-index.cwl:7:1: unrecognized extension field `http://schema.org/mainEntity`.  Did you include a $schemas section?
../eclip/cwl/samtools-index.cwl:7:1: unrecognized extension field `http://schema.org/downloadUrl`.  Did you include a $schemas section?
../eclip/cwl/samtools-index.cwl:7:1: unrecognized extension field `http://schema.org/codeRepository`.  Did you include a $schemas section?
../eclip/cwl/samtools-index.cwl:7:1: unrecognized extension field `http://schema.org/license`.  Did you include a $schemas section?
../eclip/cwl/samtools-index.cwl:7:1: unrecognized extension field `http://schema.org/isPartOf`.  Did you include a $schemas section?
../eclip/cwl/samtools-index.cwl:7:1: unrecognized extension field `http://schema.org/author`.  Did you include a $schemas section?
../eclip/cwl/star-genome.cwl:3:1: unrecognized extension field `http://schema.org/mainEntity`.  Did you include a $schemas section?
../eclip/cwl/star-genome.cwl:3:1: unrecognized extension field `http://schema.org/downloadUrl`.  Did you include a $schemas section?
../eclip/cwl/star-genome.cwl:3:1: unrecognized extension field `http://schema.org/codeRepository`.  Did you include a $schemas section?
../eclip/cwl/star-genome.cwl:3:1: unrecognized extension field `http://schema.org/isPartOf`.  Did you include a $schemas section?
../eclip/cwl/star-genome.cwl:3:1: unrecognized extension field `http://schema.org/author`.  Did you include a $schemas section?
../eclip/cwl/star-repeatmapping.cwl:3:1: unrecognized extension field `http://schema.org/mainEntity`.  Did you include a $schemas section?
../eclip/cwl/star-repeatmapping.cwl:3:1: unrecognized extension field `http://schema.org/downloadUrl`.  Did you include a $schemas section?
../eclip/cwl/star-repeatmapping.cwl:3:1: unrecognized extension field `http://schema.org/codeRepository`.  Did you include a $schemas section?
../eclip/cwl/star-repeatmapping.cwl:3:1: unrecognized extension field `http://schema.org/isPartOf`.  Did you include a $schemas section?
../eclip/cwl/star-repeatmapping.cwl:3:1: unrecognized extension field `http://schema.org/author`.  Did you include a $schemas section?

**Comment by byee4** [comment]
Hi Ben,

We don't use that feature of cwltool for most of our tools, but it is included in some of the other tools that we've modified from external sources. You can safely ignore those warnings, and we will note to remove those in the next update.

**Comment by peaceben** [comment]
Thanks!
