### ISSUE TITLE
Docker workflow for unsupported species in clipper

### ISSUE THREAD

**Issue by peaceben** [YeoLab/eclip#12]
Is there any way to use the Docker-based workflow (using e.g. ./paired_end_clip.yaml) for a species that is not natively supported by clipper? 

I read the clipper documentation and build the required annotation files for Arabidopsis in my case. A new installation with the custom annotation files should provide support for the species of interest. But this probably doesn't help when using Docker images, if i understood it correctly?

What approach would you recommend in this particular case? :+1: 

Best regards,
Ben

**Comment by byee4** [comment]
You will have to add the new species annotation to Clipper and build a new Docker image and specify that version instead.

**Comment by peaceben** [comment]
Hi!

Any chance you could provide the Dockerfile for brianyee/clipper:997fe25532a5bdcf5957f2a467ca283bbd550303
7b6a83932ad0a732a1b207c34ca986066a432ac080996d58508a3d79e1bd710a ? As the Dockerfile in the repository is not working when i try to build a new image.

Best,
Ben

**Comment by byee4** [comment]
[Dockerfile.txt](https://github.com/YeoLab/eclip/files/5219599/Dockerfile.txt)
If that doesn't work you can probably get away with using the latest version as the base image. Otherwise, might need to install the [python3 Clipper](https://github.com/YeoLab/clipper/archive/2.0.1.tar.gz)

**Comment by peaceben** [comment]
Hi thanks! What worked for me was:

[Dockerfile.txt](https://github.com/YeoLab/eclip/files/5245477/Dockerfile.txt)

**Comment by peaceben** [comment]
But i still end up with the error:
[job step_clipper] Job error:
Error collecting output for parameter 'output_tsv':

But also with these files in /.tmp/...
.peakClusters.bed
.peakClusters.bed.pickle

Seems to me like an error related to CWL/Docker as Clipper generates output in the previous mentioned files. 

I should mention i had to fix another thing before in clipper/src/main.py line 146; as in python3 binary has to be defined here:

with open(options.outfileF + ".pickle", 'w') as f: 
to
with open(options.outfileF + ".pickle", 'wb') as f:

Do you have any approaches in mind?
I would be very grateful, as i have the feeling that everything is working properly now. 

Best,
Ben

**Comment by peaceben** [comment]
What worked for me was removing the tsv output in the clipper.cwl file. The eclip pipeline is completing now without error. Thanks!
