### ISSUE TITLE
Workflow error 

### ISSUE THREAD

**Issue by pcodyhe** [YeoLab/eclip#13]
Hi, when I run the SE pipeline (cwltool --debug ./cwl/wf_get_peaks_scatter_se.cwl single_end_clip.yml ), I get the following error after make_bigwigs:

DEBUG [job make_bigwigs] initial work dir {
    "/tmp/zqsqr7yn/ENCODE4.RBM15.IP.umi.r1.fq.genome-mappedSoSo.rmDupSo.bam": [
        "/tmp/zqsqr7yn/ENCODE4.RBM15.IP.umi.r1.fq.genome-mappedSoSo.rmDupSo.bam",
        "/BPiJEa/ENCODE4.RBM15.IP.umi.r1.fq.genome-mappedSoSo.rmDupSo.bam",
        "WritableFile",
        true
    ],
    "file:///tmp/mlk18w_s/ENCODE4.RBM15.IP.umi.r1.fq.genome-mappedSoSo.rmDupSo.bam.bai": [
        "/tmp/mlk18w_s/ENCODE4.RBM15.IP.umi.r1.fq.genome-mappedSoSo.rmDupSo.bam.bai",
        "/var/lib/cwl/stgbb90b0dc-d0d1-4b10-a586-3a2186736932/ENCODE4.RBM15.IP.umi.r1.fq.genome-mappedSoSo.rmDupSo.bam.bai",
        "WritableFile",
        true
    ]
}
ERROR Workflow error:
No mandatory DockerRequirement, yet path is outside the designated output directory, also know as $(runtime.outdir): MapperEnt(resolved='/tmp/mlk18w_s/ENCODE4.RBM15.IP.umi.r1.fq.genome-mappedSoSo.rmDupSo.bam.bai', target='/var/lib/cwl/stgbb90b0dc-d0d1-4b10-a586-3a2186736932/ENCODE4.RBM15.IP.umi.r1.fq.genome-mappedSoSo.rmDupSo.bam.bai', type='WritableFile', staged=True)
Traceback (most recent call last):
  File "/home/pcodyhe/.local/lib/python3.7/site-packages/cwltool/main.py", line 1132, in main
    tool, initialized_job_order_object, runtimeContext, logger=_logger
  File "/home/pcodyhe/.local/lib/python3.7/site-packages/cwltool/executors.py", line 59, in __call__
    return self.execute(process, job_order_object, runtime_context, logger)
  File "/home/pcodyhe/.local/lib/python3.7/site-packages/cwltool/executors.py", line 150, in execute
    self.run_jobs(process, job_order_object, logger, runtime_context)
  File "/home/pcodyhe/.local/lib/python3.7/site-packages/cwltool/executors.py", line 257, in run_jobs
    job.run(runtime_context)
  File "/home/pcodyhe/.local/lib/python3.7/site-packages/cwltool/job.py", line 828, in run
    (runtime, cidfile) = self.create_runtime(env, runtimeContext)
  File "/home/pcodyhe/.local/lib/python3.7/site-packages/cwltool/docker.py", line 373, in create_runtime
    tmpdir_prefix=runtimeContext.tmpdir_prefix,
  File "/home/pcodyhe/.local/lib/python3.7/site-packages/cwltool/job.py", line 700, in add_volumes
    "$(runtime.outdir): {}".format(vol)
cwltool.errors.WorkflowException: No mandatory DockerRequirement, yet path is outside the designated output directory, also know as $(runtime.outdir): MapperEnt(resolved='/tmp/mlk18w_s/ENCODE4.RBM15.IP.umi.r1.fq.genome-mappedSoSo.rmDupSo.bam.bai', target='/var/lib/cwl/stgbb90b0dc-d0d1-4b10-a586-3a2186736932/ENCODE4.RBM15.IP.umi.r1.fq.genome-mappedSoSo.rmDupSo.bam.bai', type='WritableFile', staged=True)

I have not yet been able to figure out what is going wrong. Do you have any suggestions? Thanks!

**Comment by pcodyhe** [comment]
Seems like someone opened an issue on the CWL github page  describing a similar issue 
https://github.com/common-workflow-language/cwltool/issues/1349

**Comment by byee4** [comment]
Hi @pcodyhe thanks, it seems like the version we are using `pip install cwltool==3.0.20200706173533` will work, so perhaps dropping down to that version will work until a cwl fix is applied?

Alternatively, modifying the makebigwigs cwl (putting DockerRequirement under "requirements" instead of "hints") should get it running.

```
requirements:
  - class: ResourceRequirement
    coresMin: 1
    ramMin: 8000
  - class: InitialWorkDirRequirement
    listing:
      - entry: $(inputs.bam)
        writable: true
  - class: DockerRequirement
    dockerPull: brianyee/makebigwigfiles:0.0.3
```

**Comment by pcodyhe** [comment]
Thanks! I installed your version of CWL, which successfully resolved that issue. However, unfortunately I seem to run into another error when the pipeline tries to run clipper, I've pasted the log below.  Have you seen this before? Thanks!

INFO ['docker', 'pull', 'brianyee/clipper:997fe25532a5bdcf5957f2a467ca283bbd550303']
997fe25532a5bdcf5957f2a467ca283bbd550303: Pulling from brianyee/clipper
a1298f4ce990: Already exists
04a3282d9c4b: Already exists
9b0d3db6dc03: Already exists
8269c605f3f1: Already exists
8c29e4485dc7: Already exists
2699dd9728cb: Already exists
a0cbf26ccbce: Already exists
9878590b08b7: Already exists
2cbf34e5ccf7: Pulling fs layer
6f68a3a7162d: Pulling fs layer
ea63d9c3e6b4: Pulling fs layer
46667acffdfe: Pulling fs layer
b52f838f2dd4: Pulling fs layer
09db98582438: Pulling fs layer
46667acffdfe: Waiting
b52f838f2dd4: Waiting
09db98582438: Waiting
6f68a3a7162d: Download complete
2cbf34e5ccf7: Verifying Checksum
2cbf34e5ccf7: Download complete
2cbf34e5ccf7: Pull complete
6f68a3a7162d: Pull complete
b52f838f2dd4: Verifying Checksum
b52f838f2dd4: Download complete
ea63d9c3e6b4: Verifying Checksum
ea63d9c3e6b4: Download complete
ea63d9c3e6b4: Pull complete
46667acffdfe: Verifying Checksum
46667acffdfe: Download complete
09db98582438: Verifying Checksum
09db98582438: Download complete
46667acffdfe: Pull complete
b52f838f2dd4: Pull complete
09db98582438: Pull complete
Digest: sha256:daa75e22fdc54758f263a1331dda767d8ac9ab07bea416601f57eb78a5e1aa18
Status: Downloaded newer image for brianyee/clipper:997fe25532a5bdcf5957f2a467ca283bbd550303
DEBUG [job step_clipper] initial work dir {}
WARNING [job step_clipper] Skipping Docker software container '--memory' limit despite presence of ResourceRequirement with ramMin and/or ramMax setting. Consider running with --strict-memory-limit for increased portability assurance.
INFO [job step_clipper] /home/pcodyhe/mpm6a/results/eclip.pipeline/eclip/single_end_clip/.tmp/cwltool_interm/4689d062e83850c108894a61510c587a$ docker \
    run \
    -i \
    --mount=type=bind,source=/home/pcodyhe/mpm6a/results/eclip.pipeline/eclip/single_end_clip/.tmp/cwltool_interm/4689d062e83850c108894a61510c587a,target=/SAQZjl \
    --mount=type=bind,source=/tmp/59rnu_ps,target=/tmp \
    --mount=type=bind,source=/home/pcodyhe/mpm6a/results/eclip.pipeline/eclip/single_end_clip/.tmp/cwltool_interm/6de6120252254fb0517447a5a8634b56/ENCODE4.RBM15.IP.umi.r1.fq.genome-mappedSoSo.rmDupSo.bam,target=/var/lib/cwl/stge80d0d44-cb2e-4337-9e0f-a36e7c608322/ENCODE4.RBM15.IP.umi.r1.fq.genome-mappedSoSo.rmDupSo.bam,readonly \
    --mount=type=bind,source=/home/pcodyhe/mpm6a/results/eclip.pipeline/eclip/single_end_clip/.tmp/cwltool_interm/98acd8ed70eef5a2307ca0f346d1b2b5/ENCODE4.RBM15.IP.umi.r1.fq.genome-mappedSoSo.rmDupSo.bam.bai,target=/var/lib/cwl/stge80d0d44-cb2e-4337-9e0f-a36e7c608322/ENCODE4.RBM15.IP.umi.r1.fq.genome-mappedSoSo.rmDupSo.bam.bai,readonly \
    --workdir=/SAQZjl \
    --read-only=true \
    --user=1011:1011 \
    --rm \
    --env=TMPDIR=/tmp \
    --env=HOME=/SAQZjl \
    --cidfile=/tmp/v7petg69/20201018140304-344676.cid \
    brianyee/clipper:997fe25532a5bdcf5957f2a467ca283bbd550303 \
    clipper \
    --species \
    hg38 \
    --bam \
    /var/lib/cwl/stge80d0d44-cb2e-4337-9e0f-a36e7c608322/ENCODE4.RBM15.IP.umi.r1.fq.genome-mappedSoSo.rmDupSo.bam \
    --save-pickle \
    --outfile \
    ENCODE4.RBM15.IP.umi.r1.fq.genome-mappedSoSo.rmDupSo.peakClusters.bed
/opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "/opt/conda/bin/clipper", line 11, in <module>
    load_entry_point('clipper==0.2.0', 'console_scripts', 'clipper')()
  File "/opt/conda/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 712, in call_main
    main(options)
  File "/opt/conda/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 521, in main
    bedtool = build_transcript_data_gtf_as_structure(options.species, options.premRNA)
  File "/opt/conda/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/src/peakfinder.py", line 179, in build_transcript_data_gtf_as_structure
    x = clipper.data_file(species + ".AS.STRUCTURE.COMPILED.gff")
  File "/opt/conda/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/__init__.py", line 23, in data_file
    raise ValueError("%s does not exist" % (fn))
ValueError: /opt/conda/lib/python2.7/site-packages/clipper-0.2.0-py2.7-linux-x86_64.egg/clipper/data/hg38.AS.STRUCTURE.COMPILED.gff does not exist
INFO [job step_clipper] Max memory used: 51MiB
ERROR [job step_clipper] Job error:
("Error collecting output for parameter 'output_bed':\ncwl/clipper.cwl:79:7: Did not find output file with glob pattern: '['ENCODE4.RBM15.IP.umi.r1.fq.genome-mappedSoSo.rmDupSo.peakClusters.bed']'", {})
WARNING [job step_clipper] completed permanentFail
DEBUG [job step_clipper] outputs {}
ERROR [step step_clipper] Output is missing expected field file:///home/pcodyhe/mpm6a/results/eclip.pipeline/eclip/cwl/wf_get_peaks_se.cwl#step_clipper/output_tsv
ERROR [step step_clipper] Output is missing expected field file:///home/pcodyhe/mpm6a/results/eclip.pipeline/eclip/cwl/wf_get_peaks_se.cwl#step_clipper/output_bed
ERROR [step step_clipper] Output is missing expected field file:///home/pcodyhe/mpm6a/results/eclip.pipeline/eclip/cwl/wf_get_peaks_se.cwl#step_clipper/output_pickle
DEBUG [step step_clipper] produced output {}
WARNING [step step_clipper] completed permanentFail

**Comment by byee4** [comment]
Just saw this - can you try re-submitting the workflow but instead of 'hg38' use 'GRCh38'?

**Comment by byee4** [comment]
re-open if that doesn't work.

**Comment by katannyak** [comment]
Hi Brian,
Just an FYI, I had a similar error to @pcodyhe and resubmitted using 'GRCh38' as you suggested instead of 'hg38' for a successful (single end, single node) run.
