### ISSUE TITLE
How to install eCLIP

### ISSUE THREAD

**Issue by geng-lee** [YeoLab/eclip#14]
How to install eCLIP, I can’t find the installation method. Or you can provide an .sh file for installation.

**Comment by byee4** [comment]
Hi, yes! I'm working on getting a tutorial for spinning up our workflow on AWS, but in the meantime:

1. install [CWL](https://github.com/common-workflow-language/cwltool)
2. ensure the cwl documents are locatable by your $PATH
3. ensure the software (ie. STAR, samtools, perl) locatable by your $PATH, or install/enable Docker.

Alternatively, you can use the SOP as a guide to help you locate the commandlines used to process each step.
