### ISSUE TITLE
STAR rmRep: How to build the Star Index using *.fa files from the RepBase database.

### ISSUE THREAD

**Issue by geng-lee** [YeoLab/eclip#15]
How to build the Star Index using *.fa files from the RepBase database. There’s no *.gtf file in the RepBase that corresponds to a *.fa file, so I can’t build an index. Whether you can provide this part of the code and data files. My sample uses Mus Musculus. My email address : leegengck@163.com

_______________________________________________________________
STAR rmRep: Takes output from cutadapt round 2. Maps to human specific version of RepBase
used to remove repetitive elements, helps control for spurious artifacts from rRNA (& other)
repetitive reads.

**Comment by juuinn** [comment]
I have the same question. could you please help? my email address is xiejun1029@163.com.

**Comment by byee4** [comment]
You don't need a corresponding GTF file for repeat elements, as far as I know the GTF file is mainly used for spliced alignments, and ultimately this step is used to filter out rRNA and other shorter repetitive sequences. I would ultimately consult the [STAR manual](https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf), but for rRNA filtering, you probably won't need it.

**Comment by FionaMoon** [comment]
Yeah, I check the STAR manual.
The parameter --sjdbGTFfile was described as following:
>  STAR will extract splice junctions from this file and use them to greatly improve
accuracy of the mapping. While this is optional, and STAR can be run without annotations,using annotations is highly recommended whenever they are available.

Annotation files are not necessary for STAR index.
