### ISSUE TITLE
step_calculate_entropy

### ISSUE THREAD

**Issue by nilesh-iiita** [YeoLab/eclip#16]
Even if $PATH has bin but docker is unable to find calculate_entropy.py, and got following error

docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "calculate_entropy.py": executable file not found in $PATH: unknown.

**Comment by greysunlight** [comment]
I have similar "calculate_entropy.py": executable file not found in $PATH error like you. May because docker eclip0.6.0apyhton do not have calculate_entropy.py. I'm also looking for the way to solve this problem.

**Comment by nilesh-iiita** [comment]
Solution:
Change docker eclip:0.6.0_python to eclip:0.7.0_python in calculate_entropy.cwl file as 

hints:
  - class: DockerRequirement
    dockerPull: brianyee/eclip:0.7.0_python

example txt file is attached (remove .txt and place in cwl folder)

[calculate_entropy.cwl.txt](https://github.com/YeoLab/eclip/files/5935559/calculate_entropy.cwl.txt)
