### ISSUE TITLE
makebigwigs step on workflow

### ISSUE THREAD

**Issue by alexmondaini** [YeoLab/eclip#17]
Hi I am trying the workflow following the recommended steps: `cwltool wf_get_peaks_scatter_pe.cwl paired_end_clip.yaml` however I get an error on makebigwigs:

```
INFO [job index_r2_bam] completed success
INFO [step index_r2_bam] completed success
INFO [workflow step_ip_alignment] starting step make_bigwigs
INFO [step make_bigwigs] start
INFO Using local copy of Singularity image found in /groups/cgsd/alexandre/eclip/workflow
ERROR Workflow error, try again with --debug for more information:
No mandatory DockerRequirement, yet path is outside the designated output directory, also know as $(runtime.outdir): MapperEnt(resolved='/tmp/pbs.630316.xomics/oxl4i2mb/204_01.rep1_clip.A01.r1.fq.genome-mappedSo.rmDupSo.merged.r2.bam.bai', target='/var/lib/cwl/stgdaf3e007-c7e5-4043-b5b6-74e89ef2eb17/204_01.rep1_clip.A01.r1.fq.genome-mappedSo.rmDupSo.merged.r2.bam.bai', type='WritableFile', staged=True)

```

Is this issue related to this one ? https://github.com/YeoLab/eclip/commit/7196b92e262fe5f8acee04cb0d1b6fd23e4febdc

Thanks

**Comment by byee4** [comment]
Hi Alex, I did see that error, and was able to resolve in two ways:

Option 1. Install a previous version of cwltool (ie. pip install cwltool==3.0.20200706173533)
Option 2. Modify the tool definition (.cwl) files to make Docker mandatory. So you'll need to move the Docker definition from `hints` to `requirements`, however be careful to preserve spacing, as these files should be of YAML format (make sure the ticks line up)

**Comment by alexmondaini** [comment]
Hi Brian, I tried option 1 since I've used `cwl-runner==1.0` instead.

The error seems to be fixed but I've got another error now in `makebigwigs`:

```
ERROR [job make_bigwigs] Job error:
("Error collecting output for parameter 'negbw':\ncwl/makebigwigfiles_PE.cwl:61:7: Did not find output file with glob pattern: '['204_01.rep1_clip.A01.r1.fq.genome-mappedSo.rmDupSo.merged.r2.norm.neg.bw']'", {})
WARNING [job make_bigwigs] completed permanentFail
ERROR [step make_bigwigs] Output is missing expected field file:///groups/cgsd/alexandre/eclip/workflow/cwl/wf_clipseqcore_pe_2barcodes.cwl#make_bigwigs/posbw
ERROR [step make_bigwigs] Output is missing expected field file:///groups/cgsd/alexandre/eclip/workflow/cwl/wf_clipseqcore_pe_2barcodes.cwl#make_bigwigs/negbw
WARNING [step make_bigwigs] completed permanentFail
INFO [workflow step_ip_alignment] completed permanentFail
WARNING [step step_ip_alignment] completed permanentFail
INFO [workflow step_get_peaks] completed permanentFail
ERROR Workflow cannot make any more progress.
WARNING Final process status is permanentFail
```

**Comment by alexmondaini** [comment]
There is an extra part of the error I forgot to post here:

```
End coordinate 249059951 bigger than chr1 size of 248956422 line 160298 of /TKkoeG/204_01.rep1_input.NIL.r1.fq.genome-mappedSo.rmDupSo.r2.sorted.norm.pos.bg
End coordinate 249104571 bigger than chr1 size of 248956422 line 170431 of /TKkoeG/204_01.rep1_input.NIL.r1.fq.genome-mappedSo.rmDupSo.r2.sorted.norm.neg.bg
priming call: genomeCoverageBed -ibam /TKkoeG/204_01.rep1_input.NIL.r1.fq.genome-mappedSo.rmDupSo.r2.bam -bg -strand - -scale 0.2311648071 -g /var/lib/cwl/stga47ea8f6-5990-41d0-81ab-605661447f24/chrom.sizes -du -split  > <open file '/TKkoeG/204_01.rep1_input.NIL.r1.fq.genome-mappedSo.rmDupSo.r2.norm.pos.bg', mode 'w' at 0x7fe4b0ac8930>
priming call: bedSort /TKkoeG/204_01.rep1_input.NIL.r1.fq.genome-mappedSo.rmDupSo.r2.norm.pos.bg /TKkoeG/204_01.rep1_input.NIL.r1.fq.genome-mappedSo.rmDupSo.r2.sorted.norm.pos.bg
priming call: bedGraphToBigWig /TKkoeG/204_01.rep1_input.NIL.r1.fq.genome-mappedSo.rmDupSo.r2.sorted.norm.pos.bg /var/lib/cwl/stga47ea8f6-5990-41d0-81ab-605661447f24/chrom.sizes 204_01.rep1_input.NIL.r1.fq.genome-mappedSo.rmDupSo.r2.norm.pos.bw
priming call: genomeCoverageBed -ibam /TKkoeG/204_01.rep1_input.NIL.r1.fq.genome-mappedSo.rmDupSo.r2.bam -bg -strand + -scale -0.2311648071 -g /var/lib/cwl/stga47ea8f6-5990-41d0-81ab-605661447f24/chrom.sizes -du -split  > <open file '/TKkoeG/204_01.rep1_input.NIL.r1.fq.genome-mappedSo.rmDupSo.r2.norm.neg.bg', mode 'w' at 0x7fe4b0ac8930>
priming call: bedSort /TKkoeG/204_01.rep1_input.NIL.r1.fq.genome-mappedSo.rmDupSo.r2.norm.neg.bg /TKkoeG/204_01.rep1_input.NIL.r1.fq.genome-mappedSo.rmDupSo.r2.sorted.norm.neg.bg
priming call: bedGraphToBigWig /TKkoeG/204_01.rep1_input.NIL.r1.fq.genome-mappedSo.rmDupSo.r2.sorted.norm.neg.bg /var/lib/cwl/stga47ea8f6-5990-41d0-81ab-605661447f24/chrom.sizes 204_01.rep1_input.NIL.r1.fq.genome-mappedSo.rmDupSo.r2.norm.neg.bw
```

**Comment by byee4** [comment]
Sorry, these messages keep ending up in my spam folder. That usually means that the chrom.sizes file doesn't match with the assembly your reads were mapped to (are you using hg19 and hg19.chrom.sizes?) 

If you're using STAR to map, can you try using the '`chrNameLength.txt`' as the chrom.sizes file? It should be located inside the STAR genome index folder.

**Comment by alexmondaini** [comment]
Hi Brian,
thanks a lot for your help ! That worked for me. One last question and I will close the issue. I've passed 14 samples to `paired_end_clip.yaml` however only the workflow only finished four successfully and the others were not processed as far as I can see on my log files. Is that the normal behavior of the pipeline to run maximum 4 samples at a time ? thanks

**Comment by byee4** [comment]
Can you check that your YAML file is formatted properly? There might be an extra space or tick somewhere, causing the pipeline to only recognize four samples. You should be putting the reads corresponding to the IP into the `ip_read` field, while the sequences from the size-matched input should be in the `input_read` fields.

**Comment by byee4** [comment]
The pipeline will only call peaks on IP, hence there are more files (such as peak bedfiles) produced. But use the size matched input reads to normalize the signal across those IP-derived peaks.
