### ISSUE TITLE
Singularity image for v0.7.0

### ISSUE THREAD

**Issue by bounlu** [YeoLab/eclip#19]
Hi,

Is there a singularity image available for v0.7.0?

**Comment by byee4** [comment]
There are now containers for each step within the workflow, but if you're asking for the container with eCLIP scripts, I've made one for each custom python and perl scripts used:

brianyee/eclip:0.7.0_python
brianyee/eclip:0.7.0_perl

**Comment by bounlu** [comment]
Thanks. Those repositories seem to be not public. I can't access the scripts.

**Comment by bounlu** [comment]
I was referring to Singularity image, not Docker. Thanks.

**Comment by bounlu** [comment]
`brianyee/eclip:0.7.0_python` does not exist.
