### ISSUE TITLE
location of output files

### ISSUE THREAD

**Issue by giardine** [YeoLab/eclip#23]
I am continuing to get errors.  It would be helpful if it didn't write to /tmp because then I could see the output that is generated and better determine the error.  The current one appears to be a problem with STAR, but the error I get just says a missing final log file.  Is there a parameter I can set to tell it where to write intermediate files?

**Comment by byee4** [comment]
I believe cwltool can accept certain parameters to avoid having to write to tmp, for example our runner script uses `--cachedir` and `--outdir` to specify where the pipeline intermediates and outputs go, respectively.

**Comment by giardine** [comment]
Thanks, that helped a lot.  The STAR error was likely problems with writing to /tmp as it now goes farther.  It can't find makebigwigfiles.  With previous errors it turned out the actual program has a different name, so I am off to search for it.
