### ISSUE TITLE
It seems can't run pipeline directly in docker?

### ISSUE THREAD

**Issue by tlz4320** [YeoLab/eclip#26]
A lot of  requirements haven't been installed in your docker image.
How to use the docker image?

**Comment by byee4** [comment]
Which Docker image? Each image should work for roughly one step at a time.

**Comment by tlz4320** [comment]
Will you pack a full docker in the future? not one step one docker image.

**Comment by byee4** [comment]
It's possible we may get to it in the future, but it's currently not on our roadmap just yet.
