### ISSUE TITLE
Could you share human Repbase (fasta) with me ?

### ISSUE THREAD

**Issue by nikou123456** [YeoLab/eCLIP#27]
Hi there,

I am a PH.D student from Xiamen university. That is a great job! I want to follow your eclip pipeline to do some analysis! But I don't have access to RepBase databse. Could you share your RepBase data (hg19,fasta) with me?  I am very appreciated! 

I am looking forward to hearing from you! 

Best,
Jessica

**Comment by Zanex233** [comment]
The same request with Jessica, the link of CSI NGS Portal is not openable. And I tried the ECLIP-explorer in galaxy, it need the license.

Thanks a lot

**Comment by PinpinSui** [comment]
Hi,
Wonderful pipeline! Would you like to share the Repeat element STAR index directory(human, hg38) to suip@uthscsa.edu?
Thank you,
Pinpin Sui

**Comment by valerieT1998** [comment]
Hi,

I can't seem to find the human Repbase file required as input for hg19 (Repeat element STAR index). Can anyone help me find the download for this or instructions on how to get it?

Thanks,
Valerie

**Comment by byee4** [comment]
Hi all, here you go. This is a quite old version from RepBase (prior to the current license agreement), but importantly contains rRNA sequences which are commonly necessary to filter out prior to genome mapping. For most other species, a repeat file containing similar rRNA sequences may suffice, or you can use a more up to date (subject to current license agreements) version of the RepBase file below.

[Repbase18.05](https://external-collaborator-data.s3.us-west-1.amazonaws.com/reference-data/homo_sapiens_repbase_fixed_v2.fasta
)
