### ISSUE TITLE
eclip/0.4.0 fails due to "umi_tools not found"

### ISSUE THREAD

**Issue by shassathe** [YeoLab/eclip#3]
In the latest run on mm10, the eclip pipeline (v0.4.0) exited with the following error : 
"""
ERROR:cwltool:'umi_tools' not found
[job demux_se.cwl] completed permanentFail
"""

**Comment by byee4** [comment]
umi_tools 0.5 was trying to access ps-yeolab, which no longer exists. It's now accessing the correct path, thanks!
