### ISSUE TITLE
Where is eCLIP.img?

### ISSUE THREAD

**Issue by LucasSilvaFerreira** [YeoLab/eclip#4]
Hi,
I'm trying to reproduce the pipeline using the command below, but I can't find the  eCLIP.img.
How  can I find it?

> singularity exec \
eCLIP.img \
cwltoil \
  --jobStore file:jobStore \
  --workDir workDir \
  --outdir outDir \
  --clean never \
  --cleanWorkDir onSuccess \
  --logFile workDir/toillog.txt \
  /opt/eclip-0.3.99/cwl/wf_get_peaks_scatter_pe.cwl \
  204_RBFOX2.yaml > log.txt 2>&1

**Comment by LucasSilvaFerreira** [comment]
Just to figured out how to solve.

It looks  like a nice way to put it working... I think you guys could use it as a reference to generate  an install readme.txt


`conda create --name singularity_env`

`conda activate singularity_env`

`conda install -c conda-forge singularity`

` sudo chown root:root  /media/labdisk/data/users/my_user/bin/miniconda2/envs/singularity_clip/libexec/singularity/bin/starter-suid`


`sudo chmod 4755  /media/labdisk/data/users/my_user/bin/miniconda2/envs/singularity_clip/libexec/singularity/bin/starter-suid
`
`wget https://raw.githubusercontent.com/YeoLab/eclip/master/Singularity`

`singularity build eCLIP.img 
`

**Comment by byee4** [comment]
Hi, thanks for this! I have been trying to keep up with building the most up-to-date image however it currently is beyond my capacity right now. Truth be told there are several methods for installing Singularity, however this can serve as a nice guide for users.
